import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import NextAuthProvider from '@/providers/NextAuthProvider'
import { Navbar } from '@/components/Navbar'
import { getStrapiAPIURL } from '@/helpers/api'
import { Navigation } from '@/components/Navigation'
import { Toaster } from '@/components/ui/toaster'

// const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  display: 'auto'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function getNavbarData() {
  try {
    const response = await fetch(
      getStrapiAPIURL('navbar?populate=*'),
      { cache: 'no-store' }
    );

    return response.json();
  } catch (error) {
    throw new Error('Fail');
  }
}

export default async function RootLayout({
  children,
}: {
  session: any
  children: React.ReactNode,
  navbar: any
}) {
  const { data: navbar } = await getNavbarData();

  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextAuthProvider>
          <Navbar items={navbar} />
          {children}
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  )
}